---
gecko_sdk:
  v1.0.0:
    gcc: "4.9.3"
    iar: "7.30.1"
  v1.1.0:
    gcc: "4.9.3"
    iar: "7.80.2"
  v2.0.0:
    gcc: "4.9.3"
    iar: "7.80.2"
  v2.1.0:
    gcc: "4.9.3"
    iar: "7.80.2"
  v2.2.0:
    gcc: "4.9.3"
    iar: "7.80.2"
  v2.3.0:
    gcc: "7.2.1"
    iar: "7.80.4"
  v2.3.1:
    gcc: "7.2.1"
    iar: "7.80.4"
  v2.4.0:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.4.1:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.5.0:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.5.1:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.5.2:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.5.3:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.5.4:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.5.5:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.6.0:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.6.1:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.6.2:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.6.3:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.6.4:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.6.5:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.0:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.1:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.2:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.3:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.4:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.5:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.6:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.7:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.8:
    gcc: "7.2.1"
    iar: "8.30.1"
  v2.7.9:
    gcc: "7.2.1"
    iar: "8.30.1"
  v3.0.0:
    gcc: "7.2.1"
    iar: "8.30.1"
  v3.0.1:
    gcc: "7.2.1"
    iar: "8.30.1"
  v3.0.2:
    gcc: "7.2.1"
    iar: "8.30.1"
  v3.1.0:
    gcc: "7.2.1"
    iar: "8.30.1"
  v3.1.1:
    gcc: "7.2.1"
    iar: "8.30.1"
  v3.1.2:
    gcc: "7.2.1"
    iar: "8.30.1"
  v3.2.0:
    gcc: "10.2.0"
    iar: "8.50.91"
  v3.2.1:
    gcc: "10.2.0"
    iar: "8.50.91"
  v3.2.2:
    gcc: "10.2.0"
    iar: "8.50.91"
  v3.2.3:
    gcc: "10.2.0"
    iar: "8.50.91"
  v4.0.0:
    gcc: "10.2.Rel1"
    iar: "8.50.9"
  v4.0.1:
    gcc: "10.2.Rel1"
    iar: "8.50.9"
  v4.0.2:
    gcc: "10.2.Rel1"
    iar: "8.50.9"
  v4.1.0:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.1.1:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.1.2:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.1.3:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.1.4:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.1.5:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.1.6:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.2.0:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.2.1:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.2.2:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.2.3:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.2.4:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.2.5:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.3.0:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.3.1:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.3.2:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.3.3:
    gcc: "10.3.Rel1"
    iar: "9.20.4"
  v4.4.0:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.1:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.2:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.3:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.4:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.5:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.6:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
simplicity_sdk:
  v2024.6.0:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2024.6.1:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2024.6.2:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2024.6.3:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2024.12.0:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2024.12.1:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2024.12.2:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2024.12.3:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2025.6.0:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2025.6.1:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
