---
gecko_sdk:
  v4.0.0:
    gcc: "10.2.Rel1"
    iar: "8.50.9"
  v4.0.1:
    gcc: "10.2.Rel1"
    iar: "8.50.9"
  v4.0.2:
    gcc: "10.2.Rel1"
    iar: "8.50.9"
  v4.1.0:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.1.1:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.1.2:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.1.3:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.1.4:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.1.5:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.1.6:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.2.0:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.2.1:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.2.2:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.2.3:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.2.4:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.2.5:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.2.6:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.3.0:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.3.1:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.3.2:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.3.3:
    gcc: "12.3.Rel1"
    iar: "9.20.4"
  v4.4.0:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.1:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.2:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.3:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v4.4.4:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
simplicity_sdk:
  v2024.6.0:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
  v2024.6.1:
    gcc: "12.2.Rel1"
    iar: "9.40.1"
